"""Tests for validate/semantic/identity_assets.py + the CLI wrapper."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest
from pydantic import ValidationError

from trace_engine.validate.schema import (
    Asset,
    AssetsDocument,
    HasAccessEntry,
    IdentityAssetsDocument,
    IdentityEntry,
)
from trace_engine.validate.semantic.identity_assets import check_identity_assets

REPO = Path(__file__).parent.parent
CMD = REPO / "cmd" / "validate_identity_assets.py"


# ---------------------------------------------------------------------------
# Pydantic schema
# ---------------------------------------------------------------------------


class TestSchema:
    def test_minimal_identity(self):
        ident = IdentityEntry(id="id-x", name="X")
        assert ident.identity_class == "group"
        assert ident.sectors == []

    def test_identity_class_validation_rejects_unknown(self):
        with pytest.raises(ValidationError):
            IdentityEntry(id="id-x", name="X", identity_class="bogus")

    def test_access_level_default_is_read(self):
        edge = HasAccessEntry(identity_id="id-x", asset_id="asset-1")
        assert edge.access_level == "read"

    def test_granted_revoked_inversion_rejected(self):
        with pytest.raises(ValidationError, match="must precede"):
            HasAccessEntry(
                identity_id="id-x",
                asset_id="asset-1",
                granted_at="2024-12-01",
                revoked_at="2024-01-01",
            )

    def test_high_value_impersonation_flag_defaults_false(self):
        """Initiative C Phase 2 (BEACON 0.13.0 / TRACE 1.6.0): the new flag
        defaults to False so BEACON 0.12.x identity_assets without it
        remain valid."""
        ident = IdentityEntry(id="id-x", name="X")
        assert ident.is_high_value_impersonation_target is False
        assert ident.impersonation_risk_factors == []

    def test_high_value_impersonation_flag_roundtrips(self):
        ident = IdentityEntry(
            id="id-cfo",
            name="Sample Victim CFO",
            identity_class="individual",
            roles=["cfo"],
            is_high_value_impersonation_target=True,
            impersonation_risk_factors=["executive", "public-facing-brand"],
        )
        assert ident.is_high_value_impersonation_target is True
        assert ident.impersonation_risk_factors == ["executive", "public-facing-brand"]

    def test_document_accepts_optional_comment_field(self):
        # BEACON's generator emits a `_comment` hint at the top level;
        # IdentityAssetsDocument uses `extra='ignore'` to accept it.
        doc = IdentityAssetsDocument.model_validate(
            {
                "version": 1,
                "_comment": "Generated by BEACON ...",
                "identities": [],
                "has_access": [],
            }
        )
        assert doc.version == 1


# ---------------------------------------------------------------------------
# Cross-reference (semantic) checks
# ---------------------------------------------------------------------------


def _assets_doc(asset_ids: list[str]) -> AssetsDocument:
    return AssetsDocument(
        assets=[Asset(id=aid, name=aid) for aid in asset_ids],
    )


class TestCrossReference:
    def test_clean_doc_yields_no_findings(self):
        ia = IdentityAssetsDocument(
            identities=[IdentityEntry(id="id-x", name="X")],
            has_access=[HasAccessEntry(identity_id="id-x", asset_id="asset-1")],
        )
        a = _assets_doc(["asset-1"])
        findings = check_identity_assets(ia, a)
        assert findings == []

    def test_dangling_identity_id_is_error(self):
        ia = IdentityAssetsDocument(
            identities=[],
            has_access=[HasAccessEntry(identity_id="id-ghost", asset_id="asset-1")],
        )
        a = _assets_doc(["asset-1"])
        findings = check_identity_assets(ia, a)
        codes = [f.code for f in findings]
        assert "HAS_ACCESS_REF_IDENTITY" in codes

    def test_dangling_asset_id_is_error(self):
        ia = IdentityAssetsDocument(
            identities=[IdentityEntry(id="id-x", name="X")],
            has_access=[HasAccessEntry(identity_id="id-x", asset_id="asset-ghost")],
        )
        a = _assets_doc(["asset-1"])
        findings = check_identity_assets(ia, a)
        codes = [f.code for f in findings]
        assert "HAS_ACCESS_REF_ASSET" in codes

    def test_duplicate_identity_id_is_error(self):
        ia = IdentityAssetsDocument(
            identities=[
                IdentityEntry(id="id-x", name="X"),
                IdentityEntry(id="id-x", name="X (dup)"),
            ],
            has_access=[],
        )
        a = _assets_doc([])
        findings = check_identity_assets(ia, a)
        assert any(f.code == "IDENTITY_ID_NOT_UNIQUE" for f in findings)

    def test_duplicate_access_pair_is_warning(self):
        ia = IdentityAssetsDocument(
            identities=[IdentityEntry(id="id-x", name="X")],
            has_access=[
                HasAccessEntry(identity_id="id-x", asset_id="asset-1"),
                HasAccessEntry(
                    identity_id="id-x",
                    asset_id="asset-1",
                    access_level="admin",
                ),
            ],
        )
        a = _assets_doc(["asset-1"])
        findings = check_identity_assets(ia, a)
        warns = [f for f in findings if f.severity == "warning"]
        assert any(f.code == "HAS_ACCESS_DUPLICATE_PAIR" for f in warns)


# ---------------------------------------------------------------------------
# CLI exit codes — full process spawn against a real validator binary.
# ---------------------------------------------------------------------------


def _write(path: Path, payload: dict) -> Path:
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def _clean_files(tmp_path: Path) -> tuple[Path, Path]:
    ia = _write(
        tmp_path / "identity_assets.json",
        {
            "version": 1,
            "identities": [{"id": "id-x", "name": "X"}],
            "has_access": [{"identity_id": "id-x", "asset_id": "asset-1"}],
        },
    )
    a = _write(
        tmp_path / "assets.json",
        {
            "network_segments": [],
            "security_controls": [],
            "assets": [{"id": "asset-1", "name": "Asset 1"}],
            "asset_connections": [],
            "asset_vulnerabilities": [],
            "actor_targets": [],
        },
    )
    return ia, a


class TestCli:
    def test_exit_zero_on_clean(self, tmp_path: Path):
        ia, a = _clean_files(tmp_path)
        result = subprocess.run(
            [sys.executable, str(CMD), "--identity-assets", str(ia), "--assets", str(a)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr
        assert "errors=0" in result.stdout

    def test_exit_one_on_dangling_asset(self, tmp_path: Path):
        ia = _write(
            tmp_path / "identity_assets.json",
            {
                "version": 1,
                "identities": [{"id": "id-x", "name": "X"}],
                "has_access": [{"identity_id": "id-x", "asset_id": "asset-ghost"}],
            },
        )
        a = _write(
            tmp_path / "assets.json",
            {
                "network_segments": [],
                "security_controls": [],
                "assets": [{"id": "asset-1", "name": "Asset 1"}],
                "asset_connections": [],
                "asset_vulnerabilities": [],
                "actor_targets": [],
            },
        )
        result = subprocess.run(
            [sys.executable, str(CMD), "--identity-assets", str(ia), "--assets", str(a)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 1
        assert "errors=" in result.stdout
