"""Tests for validate/semantic/user_accounts.py + the CLI wrapper."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest
from pydantic import ValidationError

from trace_engine.validate.schema import (
    AccountOnAssetEntry,
    Asset,
    AssetsDocument,
    IdentityAssetsDocument,
    IdentityEntry,
    UserAccountEntry,
    UserAccountsDocument,
)
from trace_engine.validate.semantic.user_accounts import check_user_accounts

REPO = Path(__file__).parent.parent
CMD = REPO / "cmd" / "validate_user_accounts.py"


def _assets_doc(asset_ids: list[str]) -> AssetsDocument:
    return AssetsDocument(assets=[Asset(id=aid, name=aid) for aid in asset_ids])


def _identity_assets_doc(identity_ids: list[str]) -> IdentityAssetsDocument:
    return IdentityAssetsDocument(
        identities=[IdentityEntry(id=ident, name=ident) for ident in identity_ids],
    )


# ---------------------------------------------------------------------------
# Pydantic schema
# ---------------------------------------------------------------------------


class TestSchema:
    def test_minimal_user_account(self):
        ua = UserAccountEntry(id="ua-x", account_login="x")
        assert ua.account_type == "other"
        assert ua.is_privileged is False
        assert ua.is_service_account is False

    def test_account_type_validation_rejects_unknown(self):
        with pytest.raises(ValidationError):
            UserAccountEntry(id="ua-x", account_login="x", account_type="bogus")

    def test_first_seen_after_last_seen_rejected(self):
        with pytest.raises(ValidationError, match="must precede"):
            AccountOnAssetEntry(
                user_account_id="ua-x",
                asset_id="asset-1",
                first_seen="2024-12-01",
                last_seen="2024-01-01",
            )

    def test_document_accepts_optional_comment_field(self):
        doc = UserAccountsDocument.model_validate(
            {
                "version": 1,
                "_comment": "Generated by BEACON ...",
                "user_accounts": [],
                "account_on_asset": [],
            }
        )
        assert doc.version == 1


# ---------------------------------------------------------------------------
# Cross-reference (semantic) checks
# ---------------------------------------------------------------------------


class TestCrossReference:
    def test_clean_doc_yields_no_findings(self):
        doc = UserAccountsDocument(
            user_accounts=[UserAccountEntry(id="ua-x", account_login="x")],
            account_on_asset=[AccountOnAssetEntry(user_account_id="ua-x", asset_id="asset-1")],
        )
        a = _assets_doc(["asset-1"])
        assert check_user_accounts(doc, a) == []

    def test_dangling_user_account_id_is_error(self):
        doc = UserAccountsDocument(
            user_accounts=[],
            account_on_asset=[AccountOnAssetEntry(user_account_id="ua-ghost", asset_id="asset-1")],
        )
        a = _assets_doc(["asset-1"])
        codes = [f.code for f in check_user_accounts(doc, a)]
        assert "ACCOUNT_ON_ASSET_REF_USER_ACCOUNT" in codes

    def test_dangling_asset_id_is_error(self):
        doc = UserAccountsDocument(
            user_accounts=[UserAccountEntry(id="ua-x", account_login="x")],
            account_on_asset=[AccountOnAssetEntry(user_account_id="ua-x", asset_id="asset-ghost")],
        )
        a = _assets_doc(["asset-1"])
        codes = [f.code for f in check_user_accounts(doc, a)]
        assert "ACCOUNT_ON_ASSET_REF_ASSET" in codes

    def test_duplicate_user_account_id_is_error(self):
        doc = UserAccountsDocument(
            user_accounts=[
                UserAccountEntry(id="ua-x", account_login="x"),
                UserAccountEntry(id="ua-x", account_login="x2"),
            ],
            account_on_asset=[],
        )
        codes = [f.code for f in check_user_accounts(doc, _assets_doc([]))]
        assert "USER_ACCOUNT_ID_NOT_UNIQUE" in codes

    def test_duplicate_account_asset_pair_is_warning(self):
        doc = UserAccountsDocument(
            user_accounts=[UserAccountEntry(id="ua-x", account_login="x")],
            account_on_asset=[
                AccountOnAssetEntry(user_account_id="ua-x", asset_id="asset-1"),
                AccountOnAssetEntry(user_account_id="ua-x", asset_id="asset-1"),
            ],
        )
        all_findings = check_user_accounts(doc, _assets_doc(["asset-1"]))
        warns = [f for f in all_findings if f.severity == "warning"]
        assert any(f.code == "ACCOUNT_ON_ASSET_DUPLICATE_PAIR" for f in warns)


class TestIdentityCrossReference:
    def test_unknown_identity_id_when_doc_supplied_is_error(self):
        doc = UserAccountsDocument(
            user_accounts=[UserAccountEntry(id="ua-x", account_login="x", identity_id="id-ghost")],
            account_on_asset=[],
        )
        codes = [
            f.code
            for f in check_user_accounts(doc, _assets_doc([]), _identity_assets_doc(["id-other"]))
        ]
        assert "USER_ACCOUNT_REF_IDENTITY" in codes

    def test_unknown_identity_id_silent_when_no_identity_doc(self):
        # Without --identity-assets we don't know the identity universe,
        # so this is intentionally not an error.
        doc = UserAccountsDocument(
            user_accounts=[UserAccountEntry(id="ua-x", account_login="x", identity_id="id-ghost")],
            account_on_asset=[],
        )
        codes = [f.code for f in check_user_accounts(doc, _assets_doc([]))]
        assert "USER_ACCOUNT_REF_IDENTITY" not in codes


# ---------------------------------------------------------------------------
# CLI exit codes — full process spawn
# ---------------------------------------------------------------------------


def _write(path: Path, payload: dict) -> Path:
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def _clean_files(tmp_path: Path) -> tuple[Path, Path]:
    ua = _write(
        tmp_path / "user_accounts.json",
        {
            "version": 1,
            "user_accounts": [{"id": "ua-x", "account_login": "x"}],
            "account_on_asset": [{"user_account_id": "ua-x", "asset_id": "asset-1"}],
        },
    )
    a = _write(
        tmp_path / "assets.json",
        {
            "network_segments": [],
            "security_controls": [],
            "assets": [{"id": "asset-1", "name": "A"}],
            "asset_connections": [],
            "asset_vulnerabilities": [],
            "actor_targets": [],
        },
    )
    return ua, a


class TestCli:
    def test_exit_zero_on_clean(self, tmp_path: Path):
        ua, a = _clean_files(tmp_path)
        result = subprocess.run(
            [sys.executable, str(CMD), "--user-accounts", str(ua), "--assets", str(a)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, result.stderr
        assert "errors=0" in result.stdout

    def test_exit_one_on_dangling_asset(self, tmp_path: Path):
        ua = _write(
            tmp_path / "user_accounts.json",
            {
                "version": 1,
                "user_accounts": [{"id": "ua-x", "account_login": "x"}],
                "account_on_asset": [{"user_account_id": "ua-x", "asset_id": "asset-ghost"}],
            },
        )
        a = _write(
            tmp_path / "assets.json",
            {
                "network_segments": [],
                "security_controls": [],
                "assets": [{"id": "asset-1", "name": "A"}],
                "asset_connections": [],
                "asset_vulnerabilities": [],
                "actor_targets": [],
            },
        )
        result = subprocess.run(
            [sys.executable, str(CMD), "--user-accounts", str(ua), "--assets", str(a)],
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 1
        assert "errors=" in result.stdout
